### ISSUE TITLE
Probably StunEnchantment related crash

### ISSUE THREAD

**Issue by TheButterbrotMan** [NickName73/MoreDumbItems#2]
https://pastebin.com/bLHpGmVX

**Comment by NickName73** [comment]
Thanks for issue

**Comment by NickName73** [comment]
I can assume that this crash occurred when a non-player used the weapon (as soon as I have time I will try to fix this bug)

**Comment by TheButterbrotMan** [comment]
Would be really good. Because the crashs appears multiple times a day.

**Comment by NickName73** [comment]
Solved
